### ISSUE TITLE
Why are we using `i16` for errors?

### ISSUE THREAD

**Issue by cloudhead** [rust-amplify/io-reactor#14]
In `reactor::Error::TransportPollError` for example, and several other variants, we use `i16` for errors, instead of `io::Error`.

**Comment by dr-orlovsky** [comment]
This was done in order to allow derives on the error type

**Comment by cloudhead** [comment]
Ah I see, so the "Disconnect" error is a hangup error, not a clean shutdown I guess, since the reactor doesn't read.

I would probably then not pass the i16 at all, since it's very opaque and is an implementation detail of the poller.

**Comment by dr-orlovsky** [comment]
> Ah I see, so the "Disconnect" error is a hangup error, not a clean shutdown I guess, since the reactor doesn't read.

Yes

> I would probably then not pass the i16 at all, since it's very opaque and is an implementation detail of the poller.

Agree
