### ISSUE TITLE
Docs.rs fails to build docs with an Internal Compiler Error

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [rust-amplify/io-reactor#27]
Docs for 0.5.0 are not available on docs.rs, build logs here: https://docs.rs/crate/io-reactor/0.5.0/builds/1134663

**Comment by apiraino** [comment]
This is caused by https://github.com/rust-lang/rust/issues/123287

(a regression in the latest `rustc` in the beta release channel)

**Comment by dr-orlovsky** [comment]
Fixed in https://docs.rs/crate/io-reactor/0.5.1
